
#Only available on dedicated servers.
[server_scheduler]
	#Concurrent level for processing models. Value 0 means AUTO.
	#Range: 0 ~ 2
	ThreadCount = 0
	#Bandwidth limitation during distributing models to players.(In Mbps)
	#Range: 1 ~ 999
	BandwidthLimit = 5
	#Timeout for players to respond to synchronization. Value not greater than 10 means AUTO.(In seconds)
	#Range: 0 ~ 120
	PlayerSyncTimeout = 0
	#Whether or not players are allowed to switch models
	CanSwitchModel = true
	#Models that are not displayed on the client model selection screen
	#Example: ["default", "default_boy", "alex", "steve", "qingluka", "wine_fox", "wine_fox_jk"]
	ClientNotDisplayModels = []

